language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpcs --standard=PSR2 src
  - vendor/bin/phpunit

notifications:
  email: false

env:
  global:
  - secure: IQmBmzWHMeCFh2/BaTa7a89nsgZrEHXjYvytP7oaA0Jk/ZLy+tm9eRu8xUYC0ZIsATAB6n7wzh2Tq29aaxcB+KzBekxwLUhEEU/WpN/OrQ24i1eDtGUWASdXiMlJ9mTBhfj5sFxJ6gY2C36nlFS6qRWwruIhGPIXq6F/y3jv2kzLWpvgq0tmvc1krPPkZPXn71+N+oO3bfx+C0+ZXSxNVNFS02YLa6vOGPKZgZouMKYe/HzXbGva5pg71oZcTCVSxBkAnIXBGOVhebPp5rvAndYFgH1gfvMT2Ne3ee6G5DXqe8RA2YI+qpcoX3KhXVAVr5HXxxVyHXL9AQeXaz5tz4kZgvTW8fEwkrworcWoo+ir/sekIV5KB3XFo9/5O+MUuZiT5nr0EomCv38DxYhAr/AsUkdJqPjBgvLBhgjuf6jYdysi7nIYPZvQst0hhEWZGGXw/zV1X4CJvQvPNu6XtWHvahyE3y9hgxyMV1RNDs+75DFFArIupq15GMdph/b/L8IhtvQBk4u9lf8fmp81EcTtoYvT2m+8gIVbrokWhtZWdfpZnQUcedo5Lw189pK03mm9qXK3X92tGTp9+N1bdh36v3a5vlfKIL7yyqo2VQwg2SeuP4m68qj8EeEM9nEo0IQa7U7bi9owNtBBT37zVGjIrjxd5cQLmWruPZFZdMw=
  - secure: Le7tN+P9chgdhgl2p/X0dCGxLWX0ep6hNI41hgrIVD6rL9RYGock1Oig7SVJGumXemWASV5p4EdAkB4zz37Oec5X+KCQVXMZ5nQWMb375HlcVAj7jXX5DjSZSITyvt2DNPkcoFCDpff6YRimc4J/BrQE7G3ldPeTAZiD9QeHqxjMI9pU/3g4jtmzeQGPBw04AMLZZaTImWFeVTIdjDxqSkSRWDRu5nEqnwCQjrNJICn887rFJypVDq+yzj2UqQkbvAyPn55+vK5nSrCYBQfq3fuus13wrQJ6fJQ3dS1btdEo57BbBN//chhCGT+ZTqbl+2CrsoHkq6kkh4t4oyv9XapxqBluPFLP/VbWU6V/sDwHZtuSRjp5XmenikjHHrQR66ese8CKr08T8uWapnJ+t3KbcV1c9nIbgZc5+lsxfpTEDaadiAhjTgxXmzaGirQnNc1nfZfVItee+5buVTAIh94O9Hgn/tJ7k8WHI/Axwu4J+i9DZYc+CNq61iirMBgPyQ+jbZWvTEiWljLuxdhMAU95Kq6bh0XvVklx86BBupEep8RvaRZJqL9ZKscj+0HjfjTow4KMFYe5FTfQ0lVs7BMczydkXFhAn7XuTZhR5cwV58qSlVSiQKpPLBnk+cEQnOWgMVhiM0M5MvfbCHgvxlx6cvIjSL/VGYwMQaEa5RE=
